### PR TITLE
- Added strict/warnings pragma as reported by CPANTS.

### PR DESCRIPTION
**Pull request by manwar**
Hi @mschout 

Please review the PR.

Many Thanks.
Best Regards,
Mohammad S Anwar

### CODE REVIEW

**Comment by mschout** [comment]
Merged thanks!

**Comment by karenetheridge** [comment]
BTW this change caused https://github.com/mschout/perl-text-template/issues/9

It is not always harmless to introduce strict+warnings into existing code.

**Comment by mschout** [comment]
Ugh.  I'll look at this today.

**Comment by mschout** [comment]
Fixed in v1.51

**Pull request merged**
